
import { User, Post, PostVisibility, StoreItem, StableListing } from './types';

export const CURRENT_USER_ID = 'admin-jtothek319';

export const APP_URL = import.meta.env.VITE_APP_URL || (typeof window !== 'undefined' ? window.location.origin : 'https://www.sharebares.com');

export const APP_LOGO_URL = '/logo.png';

export const MOCK_STABLE_LISTINGS: StableListing[] = [
  {
    id: 'sl-1',
    userId: 'ai-jade',
    providerName: 'Jade Vixen',
    providerGender: 'female',
    services: 'In-person modeling, private shoots, companion services. Specialized in alternative and inked aesthetics.',
    city: 'Miami',
    importantInfo: 'Discretion is guaranteed. Heavily inked, alternative style.',
    pricing: '$500/hr',
    contactInfo: 'Phone/Text: @jadevixen_stable',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-2',
    userId: 'creator-2',
    providerName: 'Marcus Tech',
    providerGender: 'male',
    services: 'Private tech consulting, hardware setup, one-on-one training.',
    city: 'San Francisco',
    importantInfo: 'Available for travel. Professional settings only.',
    pricing: '$200/hr',
    contactInfo: 'Signal: +1-555-TECH',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-3',
    userId: 'creator-1',
    providerName: 'Sarah Jenkins',
    providerGender: 'female',
    services: 'Live mural painting, private art lessons, custom portraits.',
    city: 'Los Angeles',
    importantInfo: 'Materials included. Booking 2 weeks in advance.',
    pricing: '$150/hr',
    contactInfo: 'Email: sarah@stable.com',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-luna',
    userId: 'luna_noir',
    providerName: 'Luna Noir',
    providerGender: 'female',
    services: 'Goth aesthetic modeling, private video chats, custom content.',
    city: 'Seattle',
    importantInfo: 'Dark, mysterious, and completely unfiltered.',
    pricing: '$300/hr',
    contactInfo: 'Signal: @luna_noir',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-sienna',
    userId: 'sienna_sun',
    providerName: 'Sienna Sun',
    providerGender: 'female',
    services: 'Bikini modeling, travel companionship, lifestyle content.',
    city: 'Miami',
    importantInfo: 'Always chasing the sun. ☀️',
    pricing: '$450/hr',
    contactInfo: 'Phone/Text: @siennasun',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-raven',
    userId: 'raven_red',
    providerName: 'Raven Red',
    providerGender: 'female',
    services: 'High fashion fetish modeling, dominance play, luxury companionship.',
    city: 'New York',
    importantInfo: 'Strictly professional, high-end only.',
    pricing: '$800/hr',
    contactInfo: 'Email: raven@ravenred.com',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-lexi',
    userId: 'lexi_lace',
    providerName: 'Lexi Lace',
    providerGender: 'female',
    services: 'Lingerie modeling, girlfriend experience, private sessions.',
    city: 'Las Vegas',
    importantInfo: 'Sweet, spicy, and everything in between.',
    pricing: '$400/hr',
    contactInfo: 'Signal: @lexilace',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-misty',
    userId: 'misty_moon',
    providerName: 'Misty Moon',
    providerGender: 'female',
    services: 'Cosplay modeling, gamer girl sessions, custom roleplay.',
    city: 'Austin',
    importantInfo: 'Level up your fantasies. 🎮✨',
    pricing: '$250/hr',
    contactInfo: 'Discord: misty_moon#0001',
    avatarUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    photos: ['https://picsum.photos/seed/sharebares-mascot-bear/800', 'https://picsum.photos/seed/sharebares-mascot-bear/800'],
    createdAt: new Date().toISOString(),
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'admin-jtothek319',
    username: 'jameson319',
    displayName: 'Jameson Admin',
    email: 'jtothek319@gmail.com',
    password: '#Caleb918',
    isBanned: false,
    avatar: 'https://picsum.photos/seed/sharebares/800',
    coverImage: 'https://picsum.photos/seed/sharebares/800',
    bio: 'System Administrator. Full access enabled.',
    isCreator: true,
    isAdmin: true,
    subscribersCount: 0,
    followingCount: 0,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'creator-1',
    username: 'sarah_art',
    displayName: 'Sarah Jenkins',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Professional digital artist. Exclusive tutorials and BTS content here.',
    location: 'Los Angeles, CA',
    occupation: 'Digital Artist',
    tagline: 'Creating worlds one pixel at a time',
    socials: {
      twitter: 'sarahart',
      instagram: 'sarahjenkins_art',
      website: 'https://sarahjenkins.art'
    },
    isCreator: true,
    subscribersCount: 850,
    followingCount: 120,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'creator-2',
    username: 'tech_guru',
    displayName: 'Marcus Tech',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Weekly deep dives into the future of tech.',
    location: 'San Francisco, CA',
    occupation: 'Tech Journalist',
    tagline: 'Decoding the future',
    socials: {
      twitter: 'marcustech',
      website: 'https://marcustech.blog'
    },
    isCreator: true,
    subscribersCount: 3200,
    followingCount: 45,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'ai-jade',
    username: 'jade_vixen',
    displayName: 'Jade Vixen',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'The inked queen of the night. 🖤 Intricate blackwork tattoos from neck to chest. Edgy, unfiltered, and always pushing boundaries. Subscribe for the content they won\'t let me post anywhere else. 🔥',
    location: 'Miami, FL',
    occupation: 'Alternative Tattoo Model',
    tagline: 'Inked, intense, and living on the edge.',
    socials: {
      twitter: 'jadevixen',
      instagram: 'jade_vixen_official',
      website: 'https://jadevixen.com'
    },
    isCreator: true,
    subscribersCount: 12500,
    followingCount: 214,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    photos: [
      { id: 'jade-p1', url: 'https://picsum.photos/seed/sharebares-mascot-bear/800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false },
      { id: 'jade-p2', url: 'https://picsum.photos/seed/sharebares-mascot-bear/800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false },
      { id: 'jade-p3', url: 'https://picsum.photos/seed/sharebares-mascot-bear/800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false }
    ],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'luna_noir',
    username: 'luna_noir',
    displayName: 'Luna Noir',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Your favorite goth nightmare. 🌙 Dark aesthetics, heavy ink, and a taste for the forbidden. Subscribe for the real darkness. 🖤',
    location: 'Seattle, WA',
    occupation: 'Alternative Model',
    tagline: 'Embrace the darkness.',
    isCreator: true,
    subscribersCount: 5400,
    followingCount: 150,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'sienna_sun',
    username: 'sienna_sun',
    displayName: 'Sienna Sun',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Always in a bikini. 👙 Sun-kissed and living my best life in Miami. Join me for beach days and wild nights. ☀️🔥',
    location: 'Miami, FL',
    occupation: 'Bikini Model',
    tagline: 'Chasing the eternal summer.',
    isCreator: true,
    subscribersCount: 8900,
    followingCount: 310,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'raven_red',
    username: 'raven_red',
    displayName: 'Raven Red',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'High fashion, higher standards. 👠 Red lips, black lace, and total control. Discover the art of elegance and edge. 💋🌹',
    location: 'New York, NY',
    occupation: 'Fashion Model',
    tagline: 'Sophistication with a bite.',
    isCreator: true,
    subscribersCount: 12000,
    followingCount: 85,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'lexi_lace',
    username: 'lexi_lace',
    displayName: 'Lexi Lace',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Soft lace, hard limits. 🎀 Your favorite girl next door with a secret. Come play in my world of silk and shadows. ✨💖',
    location: 'Las Vegas, NV',
    occupation: 'Lingerie Model',
    tagline: 'Sweet dreams and spicy realities.',
    isCreator: true,
    subscribersCount: 7200,
    followingCount: 420,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'misty_moon',
    username: 'misty_moon',
    displayName: 'Misty Moon',
    avatar: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    coverImage: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    bio: 'Leveling up your fantasies. 🎮✨ Cosplayer, gamer, and full-time dreamer. Ready for a multiplayer session? 👾💜',
    location: 'Austin, TX',
    occupation: 'Cosplayer',
    tagline: 'Your favorite player two.',
    isCreator: true,
    subscribersCount: 15000,
    followingCount: 600,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    userId: 'creator-1',
    content: 'Check out my new masterpiece! This took 40 hours to complete.',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 450,
    commentsCount: 32,
    visibility: PostVisibility.PUBLIC,
    category: 'Art',
    likedBy: [],
  },
  {
    id: 'post-2',
    userId: 'creator-1',
    content: 'Secret technique I used for the shading in my last piece.',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    likes: 120,
    commentsCount: 15,
    visibility: PostVisibility.PUBLIC,
    category: 'Art',
    likedBy: [],
  },
  {
    id: 'post-3',
    userId: 'creator-2',
    content: 'Unboxing the latest Gemini 3 Developer Kit!',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 890,
    commentsCount: 104,
    visibility: PostVisibility.PUBLIC,
    category: 'Tech',
    likedBy: [],
  },
  {
    id: 'jade-post-1',
    userId: 'ai-jade',
    content: 'The ink tells the story that words can\'t. 🖤 New set showing off the full chest piece details. Who\'s ready to see the close-ups?',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    likes: 1240,
    commentsCount: 88,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'jade-post-2',
    userId: 'ai-jade',
    content: 'ShareBares sessions. The contrast of the black ink against the neon lights is everything. 🔥😈 Full gallery now in the store.',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 3500,
    commentsCount: 245,
    visibility: PostVisibility.PRIVATE,
    category: 'Exclusive',
    likedBy: [],
  },
  {
    id: 'luna-post-1',
    userId: 'luna_noir',
    content: 'The moon is my only witness. 🌙🖤 New set dropping tonight. Who\'s staying up with me?',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 850,
    commentsCount: 45,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'sienna-post-1',
    userId: 'sienna_sun',
    content: 'Golden hour is the only hour that matters. ☀️👙 Can you handle the heat?',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 1200,
    commentsCount: 92,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'raven-post-1',
    userId: 'raven_red',
    content: 'Power is the ultimate aphrodisiac. 👠💄 New luxury set available now.',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 2100,
    commentsCount: 156,
    visibility: PostVisibility.PUBLIC,
    category: 'Fashion',
    likedBy: [],
  },
  {
    id: 'lexi-post-1',
    userId: 'lexi_lace',
    content: 'Silk and secrets. 🎀✨ What do you think I\'m hiding?',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 980,
    commentsCount: 64,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'misty-post-1',
    userId: 'misty_moon',
    content: 'New skin unlocked! 🎮👾 Do you like my latest cosplay?',
    mediaUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 3400,
    commentsCount: 210,
    visibility: PostVisibility.PUBLIC,
    category: 'Cosplay',
    likedBy: [],
  }
];

export const MOCK_STORE_ITEMS: StoreItem[] = [
  {
    id: 's1',
    userId: 'creator-1',
    title: 'Digital Painting Masterclass',
    price: 49.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's2',
    userId: 'creator-1',
    title: 'Exclusive Art Pack - Vol 1',
    price: 19.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: [
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's3',
    userId: 'creator-2',
    title: 'Future Tech Predictions 2026',
    price: 29.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's4',
    userId: 'me-123',
    title: 'My Private Collection',
    price: 99.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'other',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jade-s1',
    userId: 'ai-jade',
    title: 'Inked & Unfiltered Collection',
    price: 34.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: [
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jade-s2',
    userId: 'ai-jade',
    title: 'Behind the Ink: The Chest Piece Story',
    price: 14.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'luna-s1',
    userId: 'luna_noir',
    title: 'ShareBares Rituals - Full Set',
    price: 24.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: [
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sienna-s1',
    userId: 'sienna_sun',
    title: 'Summer Heat - Bikini Collection',
    price: 19.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'raven-s1',
    userId: 'raven_red',
    title: 'The Red Room - Luxury Fetish',
    price: 49.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lexi-s1',
    userId: 'lexi_lace',
    title: 'Lace & Leather - Private Session',
    price: 29.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: ['https://picsum.photos/seed/sharebares-mascot-bear/800'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'misty-s1',
    userId: 'misty_moon',
    title: 'Fantasy Quest - Cosplay Gallery',
    price: 14.99,
    thumbnailUrl: 'https://picsum.photos/seed/sharebares-mascot-bear/800',
    mediaUrls: [
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800',
      'https://picsum.photos/seed/sharebares-mascot-bear/800'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  }
];
