
import { User, Post, PostVisibility, StoreItem, StableListing } from './types';

export const CURRENT_USER_ID = 'admin-jtothek319';

// CCBill Configuration
const CCBILL_CLIENT_ACCOUNT = import.meta.env.VITE_CCBILL_CLIENT_ACCOUNT || '000000';
const CCBILL_SALT = import.meta.env.VITE_CCBILL_SALT || '';

// Active stripe subscription billing payment links ($15.00/month)
export const STORE_ACTIVATION_LINK = "https://buy.stripe.com/9B65kv34LbuK0Vt1XE73G00";
export const STABLE_MEMBERSHIP_LINK = "https://buy.stripe.com/bJe3cnfRx56m0Vtaua73G01";

export const APP_URL = import.meta.env.VITE_APP_URL || (typeof window !== 'undefined' ? window.location.origin : 'https://www.sharebares.com');

export const APP_LOGO_URL = '/logo.png';

export const MOCK_STABLE_LISTINGS: StableListing[] = [
  {
    id: 'sl-1',
    userId: 'ai-jade',
    providerName: 'Jade Vixen',
    providerGender: 'female',
    services: 'In-person modeling, private shoots, companion services. Specialized in alternative and inked aesthetics.',
    city: 'Miami',
    importantInfo: 'Discretion is guaranteed. Heavily inked, alternative style.',
    contactInfo: 'Phone/Text: @jadevixen_stable',
    avatarUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-2',
    userId: 'creator-2',
    providerName: 'Marcus Tech',
    providerGender: 'male',
    services: 'Private tech consulting, hardware setup, one-on-one training.',
    city: 'San Francisco',
    importantInfo: 'Available for travel. Professional settings only.',
    contactInfo: 'Signal: +1-555-TECH',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-3',
    userId: 'creator-1',
    providerName: 'Sarah Jenkins',
    providerGender: 'female',
    services: 'Live mural painting, private art lessons, custom portraits.',
    city: 'Los Angeles',
    importantInfo: 'Materials included. Booking 2 weeks in advance.',
    contactInfo: 'Email: sarah@stable.com',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1504333638930-c8787321eee0?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-luna',
    userId: 'luna_noir',
    providerName: 'Luna Noir',
    providerGender: 'female',
    services: 'Goth aesthetic modeling, private video chats, custom content.',
    city: 'Seattle',
    importantInfo: 'Dark, mysterious, and completely unfiltered.',
    contactInfo: 'Signal: @luna_noir',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-sienna',
    userId: 'sienna_sun',
    providerName: 'Sienna Sun',
    providerGender: 'female',
    services: 'Bikini modeling, travel companionship, lifestyle content.',
    city: 'Miami',
    importantInfo: 'Always chasing the sun. ☀️',
    contactInfo: 'Phone/Text: @siennasun',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-raven',
    userId: 'raven_red',
    providerName: 'Raven Red',
    providerGender: 'female',
    services: 'High fashion fetish modeling, dominance play, luxury companionship.',
    city: 'New York',
    importantInfo: 'Strictly professional, high-end only.',
    contactInfo: 'Email: raven@ravenred.com',
    avatarUrl: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-lexi',
    userId: 'lexi_lace',
    providerName: 'Lexi Lace',
    providerGender: 'female',
    services: 'Lingerie modeling, girlfriend experience, private sessions.',
    city: 'Las Vegas',
    importantInfo: 'Sweet, spicy, and everything in between.',
    contactInfo: 'Signal: @lexilace',
    avatarUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1517230878791-4d28214057c2?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sl-misty',
    userId: 'misty_moon',
    providerName: 'Misty Moon',
    providerGender: 'female',
    services: 'Cosplay modeling, gamer girl sessions, custom roleplay.',
    city: 'Austin',
    importantInfo: 'Level up your fantasies. 🎮✨',
    contactInfo: 'Discord: misty_moon#0001',
    avatarUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400&h=400',
    photos: [
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800'
    ],
    createdAt: new Date().toISOString(),
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'admin-jtothek319',
    username: 'jameson319',
    displayName: 'Jameson Admin',
    email: 'jtothek319@gmail.com',
    password: '#Caleb918',
    isBanned: false,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200',
    bio: 'System Administrator. Full access enabled.',
    isCreator: true,
    isAdmin: true,
    isStoreActive: true,
    cashAppTag: '$jamesonadmin',
    payPalUsername: 'jamesonadmin',
    subscribersCount: 0,
    followingCount: 0,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'creator-1',
    username: 'sarah_art',
    displayName: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1504333638930-c8787321eee0?auto=format&fit=crop&q=80&w=1200',
    bio: 'Professional digital artist. Exclusive tutorials and BTS content here.',
    location: 'Los Angeles, CA',
    occupation: 'Digital Artist',
    tagline: 'Creating worlds one pixel at a time',
    socials: {
      twitter: 'sarahart',
      instagram: 'sarahjenkins_art',
      website: 'https://sarahjenkins.art'
    },
    isCreator: true,
    isStoreActive: true,
    cashAppTag: '$sarahart',
    payPalUsername: 'sarahjenkins',
    subscribersCount: 850,
    followingCount: 120,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'creator-2',
    username: 'tech_guru',
    displayName: 'Marcus Tech',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200',
    bio: 'Weekly deep dives into the future of tech.',
    location: 'San Francisco, CA',
    occupation: 'Tech Journalist',
    tagline: 'Decoding the future',
    socials: {
      twitter: 'marcustech',
      website: 'https://marcustech.blog'
    },
    isCreator: true,
    isStoreActive: true,
    cashAppTag: '$marcustech',
    payPalUsername: 'marcustech',
    subscribersCount: 3200,
    followingCount: 45,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'ai-jade',
    username: 'jade_vixen',
    displayName: 'Jade Vixen',
    avatar: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=1200',
    bio: 'The inked queen of the night. 🖤 Intricate blackwork tattoos from neck to chest. Edgy, unfiltered, and always pushing boundaries. Subscribe for the content they won\'t let me post anywhere else. 🔥',
    location: 'Miami, FL',
    occupation: 'Alternative Tattoo Model',
    tagline: 'Inked, intense, and living on the edge.',
    socials: {
      twitter: 'jadevixen',
      instagram: 'jade_vixen_official',
      website: 'https://jadevixen.com'
    },
    isCreator: true,
    isStoreActive: true,
    cashAppTag: '$jadevixen',
    payPalUsername: 'jadevixen',
    subscribersCount: 12500,
    followingCount: 214,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    photos: [
      { id: 'jade-p1', url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false },
      { id: 'jade-p2', url: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false },
      { id: 'jade-p3', url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800', type: 'image', createdAt: new Date().toISOString(), isNSFW: false }
    ],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'luna_noir',
    username: 'luna_noir',
    displayName: 'Luna Noir',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988bad197?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1200',
    bio: 'Your favorite goth nightmare. 🌙 Dark aesthetics, heavy ink, and a taste for the forbidden. Subscribe for the real darkness. 🖤',
    location: 'Seattle, WA',
    occupation: 'Alternative Model',
    tagline: 'Embrace the darkness.',
    isCreator: true,
    isStoreActive: true,
    subscribersCount: 5400,
    followingCount: 150,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'sienna_sun',
    username: 'sienna_sun',
    displayName: 'Sienna Sun',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=1200',
    bio: 'Always in a bikini. 👙 Sun-kissed and living my best life in Miami. Join me for beach days and wild nights. ☀️🔥',
    location: 'Miami, FL',
    occupation: 'Bikini Model',
    tagline: 'Chasing the eternal summer.',
    isCreator: true,
    isStoreActive: true,
    subscribersCount: 8900,
    followingCount: 310,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'raven_red',
    username: 'raven_red',
    displayName: 'Raven Red',
    avatar: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1542285638-d43dbcd26090?auto=format&fit=crop&q=80&w=1200',
    bio: 'High fashion, higher standards. 👠 Red lips, black lace, and total control. Discover the art of elegance and edge. 💋🌹',
    location: 'New York, NY',
    occupation: 'Fashion Model',
    tagline: 'Sophistication with a bite.',
    isCreator: true,
    isStoreActive: true,
    subscribersCount: 12000,
    followingCount: 85,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'lexi_lace',
    username: 'lexi_lace',
    displayName: 'Lexi Lace',
    avatar: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1517230878791-4d28214057c2?auto=format&fit=crop&q=80&w=1200',
    bio: 'Soft lace, hard limits. 🎀 Your favorite girl next door with a secret. Come play in my world of silk and shadows. ✨💖',
    location: 'Las Vegas, NV',
    occupation: 'Lingerie Model',
    tagline: 'Sweet dreams and spicy realities.',
    isCreator: true,
    isStoreActive: true,
    subscribersCount: 7200,
    followingCount: 420,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  },
  {
    id: 'misty_moon',
    username: 'misty_moon',
    displayName: 'Misty Moon',
    avatar: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=400&h=400',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=1200',
    bio: 'Leveling up your fantasies. 🎮✨ Cosplayer, gamer, and full-time dreamer. Ready for a multiplayer session? 👾💜',
    location: 'Austin, TX',
    occupation: 'Cosplayer',
    tagline: 'Your favorite player two.',
    isCreator: true,
    isStoreActive: true,
    subscribersCount: 15000,
    followingCount: 600,
    friendIds: [],
    pendingFriendRequestsSent: [],
    pendingFriendRequestsReceived: [],
    fwbIds: [],
    pendingFwbRequestsSent: [],
    pendingFwbRequestsReceived: [],
    fwbRequestsResetDate: new Date().toISOString(),
    fwbRequestsSentCount: 0,
    fanIds: [],
    profileCustomization: {},
    photos: [],
    storeUploads: [],
    blockedUserIds: [],
    likedPostIds: [],
    settings: {
      pushNotifications: true,
      emailNotifications: true,
      profileVisibility: 'public',
      messagingPrivacy: 'everyone'
    }
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    userId: 'creator-1',
    content: 'Check out my new masterpiece! This took 40 hours to complete.',
    mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 450,
    commentsCount: 32,
    visibility: PostVisibility.PUBLIC,
    category: 'Art',
    likedBy: [],
  },
  {
    id: 'post-2',
    userId: 'creator-1',
    content: 'Secret technique I used for the shading in my last piece.',
    mediaUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    likes: 120,
    commentsCount: 15,
    visibility: PostVisibility.PUBLIC,
    category: 'Art',
    likedBy: [],
  },
  {
    id: 'post-3',
    userId: 'creator-2',
    content: 'Unboxing the latest Gemini 3 Developer Kit!',
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 890,
    commentsCount: 104,
    visibility: PostVisibility.PUBLIC,
    category: 'Tech',
    likedBy: [],
  },
  {
    id: 'jade-post-1',
    userId: 'ai-jade',
    content: 'The ink tells the story that words can\'t. 🖤 New set showing off the full chest piece details. Who\'s ready to see the close-ups?',
    mediaUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    likes: 1240,
    commentsCount: 88,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'jade-post-2',
    userId: 'ai-jade',
    content: 'ShareBares sessions. The contrast of the black ink against the neon lights is everything. 🔥😈 Full gallery now in the store.',
    mediaUrl: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 3500,
    commentsCount: 245,
    visibility: PostVisibility.PUBLIC,
    category: 'Exclusive',
    likedBy: [],
  },
  {
    id: 'luna-post-1',
    userId: 'luna_noir',
    content: 'The moon is my only witness. 🌙🖤 New set dropping tonight. Who\'s staying up with me?',
    mediaUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 850,
    commentsCount: 45,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'sienna-post-1',
    userId: 'sienna_sun',
    content: 'Golden hour is the only hour that matters. ☀️👙 Can you handle the heat?',
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 1200,
    commentsCount: 92,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'raven-post-1',
    userId: 'raven_red',
    content: 'Power is the ultimate aphrodisiac. 👠💄 New luxury set available now.',
    mediaUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 2100,
    commentsCount: 156,
    visibility: PostVisibility.PUBLIC,
    category: 'Fashion',
    likedBy: [],
  },
  {
    id: 'lexi-post-1',
    userId: 'lexi_lace',
    content: 'Silk and secrets. 🎀✨ What do you think I\'m hiding?',
    mediaUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 980,
    commentsCount: 64,
    visibility: PostVisibility.PUBLIC,
    category: 'Lifestyle',
    likedBy: [],
  },
  {
    id: 'misty-post-1',
    userId: 'misty_moon',
    content: 'New skin unlocked! 🎮👾 Do you like my latest cosplay?',
    mediaUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    mediaType: 'image',
    createdAt: new Date().toISOString(),
    likes: 3400,
    commentsCount: 210,
    visibility: PostVisibility.PUBLIC,
    category: 'Cosplay',
    likedBy: [],
  }
];

export const MOCK_STORE_ITEMS: StoreItem[] = [
  {
    id: 's1',
    userId: 'creator-1',
    title: 'Digital Painting Masterclass',
    thumbnailUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&q=80&w=1200'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's2',
    userId: 'creator-1',
    title: 'Exclusive Art Pack - Vol 1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=600',
    mediaUrls: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=1200'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's3',
    userId: 'creator-2',
    title: 'Future Tech Predictions 2026',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 's4',
    userId: 'me-123',
    title: 'My Private Collection',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1200'],
    type: 'other',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jade-s1',
    userId: 'ai-jade',
    title: 'Inked & Unfiltered Collection',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=600',
    mediaUrls: [
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1200'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jade-s2',
    userId: 'ai-jade',
    title: 'Behind the Ink: The Chest Piece Story',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590246814883-57f511e76533?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'luna-s1',
    userId: 'luna_noir',
    title: 'ShareBares Rituals - Full Set',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=600',
    mediaUrls: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=1200'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sienna-s1',
    userId: 'sienna_sun',
    title: 'Summer Heat - Bikini Collection',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'raven-s1',
    userId: 'raven_red',
    title: 'The Red Room - Luxury Fetish',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lexi-s1',
    userId: 'lexi_lace',
    title: 'Lace & Leather - Private Session',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=600',
    mediaUrls: ['https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'],
    type: 'video',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'misty-s1',
    userId: 'misty_moon',
    title: 'Fantasy Quest - Cosplay Gallery',
    thumbnailUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=600',
    mediaUrls: [
      'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=1200'
    ],
    type: 'picture_pack',
    createdAt: new Date().toISOString(),
  }
];
